export type BodyType = "sedan" | "suv" | "crossover" | "coupe" | "hatchback";
export type Fuel = "gasoline" | "diesel" | "electric" | "hybrid";
export type Transmission = "auto" | "manual";

export type Car = {
  id: string;
  name: string;
  brand: string;
  body: BodyType;
  fuel: Fuel;
  transmission: Transmission;
  price: number;
  year: number;
  image: string;
  engine: string;
  power: number;
  acceleration: number;
  topSpeed: number;
  consumption: string;
  description: string;
  features: string[];
};

export const BODY_LABELS: Record<BodyType, string> = {
  sedan: "Седан",
  suv: "Внедорожник",
  crossover: "Кроссовер",
  coupe: "Купе",
  hatchback: "Хэтчбек",
};

export const FUEL_LABELS: Record<Fuel, string> = {
  gasoline: "Бензин",
  diesel: "Дизель",
  electric: "Электро",
  hybrid: "Гибрид",
};

export const TRANSMISSION_LABELS: Record<Transmission, string> = {
  auto: "Автомат",
  manual: "Механика",
};

const F = {
  premiumSuv: [
    "Полный привод",
    "Пневмоподвеска",
    "Кожаный салон Nappa",
    "Премиальная аудиосистема",
    "Камера 360°",
    "Адаптивный круиз-контроль",
    "Панорамная крыша",
    "Вентиляция передних сидений",
  ],
  premiumSedan: [
    "Кожаный салон",
    "Подогрев и вентиляция сидений",
    "Премиальная аудиосистема",
    "Камера 360°",
    "Адаптивный круиз-контроль",
    "LED-матричные фары",
    "Панорамная крыша",
    "Беспроводная зарядка",
  ],
  midCrossover: [
    "Полный привод (опционально)",
    "Комбинированный салон",
    "Камера заднего вида",
    "Климат-контроль",
    "Подогрев передних сидений",
    "Адаптивный круиз-контроль",
    "Беспроводная зарядка",
    "LED-оптика",
  ],
  massSedan: [
    "Климат-контроль",
    "Подогрев передних сидений",
    "Камера заднего вида",
    "LED-оптика",
    "Apple CarPlay / Android Auto",
    "Парктроник передний и задний",
    "Бесключевой доступ",
    "Круиз-контроль",
  ],
  budgetCrossover: [
    "Климат-контроль",
    "Подогрев передних сидений",
    "Камера заднего вида",
    'Мультимедиа 10" с навигацией',
    "LED-оптика",
    "Электрозеркала с подогревом",
    "Бесключевой доступ",
    "Парктроник",
  ],
  hatchback: [
    "Климат-контроль",
    "Подогрев передних сидений",
    "Камера заднего вида",
    "LED-оптика",
    "Apple CarPlay / Android Auto",
    "Круиз-контроль",
    "Электростеклоподъёмники",
    "USB-порты",
  ],
  sportsCoupe: [
    "Спортивная подвеска",
    "Спортивные сиденья с поддержкой",
    "Карбоновые элементы салона",
    "Премиальная аудиосистема",
    "Кожаный салон",
    "LED-матричные фары",
    "Launch Control",
    "Адаптивный круиз-контроль",
  ],
  ev: (range: number, fastCharge: string) => [
    `Запас хода ${range} км`,
    `Быстрая зарядка ${fastCharge}`,
    "Тепловой насос",
    "Панорамная крыша",
    "Премиальная аудиосистема",
    "Камера 360°",
    "Адаптивный круиз-контроль",
    "Беспроводная зарядка",
  ],
};

const U = "https://images.unsplash.com/photo-";
const Q = "?auto=format&fit=crop&w=1600&q=80";
const IMG = {
  suv1: `${U}1606664515524-ed2f786a0bd6${Q}`,
  suv2: `${U}1568844293986-8d0400bd4745${Q}`,
  suv3: `${U}1614200187524-dc4b892acf16${Q}`,
  suv4: `${U}1612825173281-9a193378527e${Q}`,
  sedan1: `${U}1555215695-3004980ad54e${Q}`,
  sedan2: `${U}1583121274602-3e2820c69888${Q}`,
  sedan3: `${U}1542362567-b07e54358753${Q}`,
  coupe1: `${U}1503376780353-7e6692767b70${Q}`,
  coupe2: `${U}1494976388531-d1058494cdd8${Q}`,
  coupe3: `${U}1492144534655-ae79c964c9d7${Q}`,
  ev1: `${U}1617788138017-80ad40651399${Q}`,
  ev2: `${U}1580273916550-e323be2ae537${Q}`,
};

export const cars: Car[] = [
  // ===== Featured (показываются на главной первыми) =====
  {
    id: "bmw-x5",
    name: "X5 xDrive40i",
    brand: "BMW",
    body: "suv",
    fuel: "gasoline",
    transmission: "auto",
    price: 8200000,
    year: 2026,
    image: IMG.suv1,
    engine: "3.0 R6 TwinPower Turbo",
    power: 340,
    acceleration: 5.5,
    topSpeed: 243,
    consumption: "8.5 л/100 км",
    description:
      "Эталон премиальных внедорожников. Сбалансированная динамика, отделка Nappa и адаптивная пневмоподвеска по умолчанию.",
    features: F.premiumSuv,
  },
  {
    id: "tesla-model-y",
    name: "Model Y Long Range",
    brand: "Tesla",
    body: "crossover",
    fuel: "electric",
    transmission: "auto",
    price: 7800000,
    year: 2026,
    image: IMG.ev1,
    engine: "Два электромотора 378 кВт",
    power: 514,
    acceleration: 4.8,
    topSpeed: 217,
    consumption: "16.9 кВт·ч/100 км",
    description:
      "Самый продаваемый электрокроссовер мира. Полный привод, минималистичный салон, обновления по воздуху.",
    features: F.ev(533, "до 80% за 27 мин"),
  },
  {
    id: "porsche-911",
    name: "911 Carrera",
    brand: "Porsche",
    body: "coupe",
    fuel: "gasoline",
    transmission: "auto",
    price: 18500000,
    year: 2026,
    image: IMG.coupe1,
    engine: "3.0 H6 Twin-Turbo",
    power: 394,
    acceleration: 4.1,
    topSpeed: 294,
    consumption: "10.1 л/100 км",
    description:
      "Икона спорткаров с 1963 года. Идеальная развесовка, легендарная управляемость, ежедневная пригодность.",
    features: F.sportsCoupe,
  },
  {
    id: "toyota-camry",
    name: "Camry 2.5 Prestige",
    brand: "Toyota",
    body: "sedan",
    fuel: "gasoline",
    transmission: "auto",
    price: 4300000,
    year: 2026,
    image: IMG.sedan1,
    engine: "2.5 Dynamic Force",
    power: 200,
    acceleration: 8.9,
    topSpeed: 210,
    consumption: "7.6 л/100 км",
    description:
      "Бестселлер бизнес-класса. Знаменитая надёжность Toyota, просторный салон, низкая стоимость владения.",
    features: F.massSedan,
  },

  // ===== Премиум-внедорожники =====
  {
    id: "bmw-x7",
    name: "X7 xDrive40i",
    brand: "BMW",
    body: "suv",
    fuel: "gasoline",
    transmission: "auto",
    price: 12500000,
    year: 2026,
    image: IMG.suv2,
    engine: "3.0 R6 TwinPower Turbo",
    power: 381,
    acceleration: 6.1,
    topSpeed: 245,
    consumption: "9.1 л/100 км",
    description:
      "Флагманский внедорожник BMW. Семиместный салон, пневмоподвеска, премиальная отделка Merino.",
    features: F.premiumSuv,
  },
  {
    id: "mercedes-gle",
    name: "GLE 450 4MATIC",
    brand: "Mercedes-Benz",
    body: "suv",
    fuel: "gasoline",
    transmission: "auto",
    price: 9100000,
    year: 2026,
    image: IMG.suv3,
    engine: "3.0 R6 EQ Boost",
    power: 381,
    acceleration: 5.7,
    topSpeed: 250,
    consumption: "9.2 л/100 км",
    description:
      "Премиальный SUV с мягким гибридом 48V. Воздушная подвеска AIRMATIC, мультимедиа MBUX последнего поколения.",
    features: F.premiumSuv,
  },
  {
    id: "mercedes-gls",
    name: "GLS 450 4MATIC",
    brand: "Mercedes-Benz",
    body: "suv",
    fuel: "gasoline",
    transmission: "auto",
    price: 14200000,
    year: 2026,
    image: IMG.suv1,
    engine: "3.0 R6 EQ Boost",
    power: 381,
    acceleration: 6.2,
    topSpeed: 250,
    consumption: "9.8 л/100 км",
    description:
      "S-Class среди SUV. Семиместный салон, E-Active Body Control, премиум-аудио Burmester.",
    features: F.premiumSuv,
  },
  {
    id: "audi-q7",
    name: "Q7 55 TFSI quattro",
    brand: "Audi",
    body: "suv",
    fuel: "gasoline",
    transmission: "auto",
    price: 9400000,
    year: 2026,
    image: IMG.suv2,
    engine: "3.0 V6 TFSI",
    power: 340,
    acceleration: 5.9,
    topSpeed: 250,
    consumption: "9.3 л/100 км",
    description:
      "Семиместный премиум-SUV с фирменным quattro. Цифровая приборная панель Virtual Cockpit, активные подголовники.",
    features: F.premiumSuv,
  },
  {
    id: "porsche-cayenne",
    name: "Cayenne",
    brand: "Porsche",
    body: "suv",
    fuel: "gasoline",
    transmission: "auto",
    price: 13500000,
    year: 2026,
    image: IMG.suv3,
    engine: "3.0 V6 Turbo",
    power: 353,
    acceleration: 6.0,
    topSpeed: 248,
    consumption: "10.5 л/100 км",
    description:
      "Спортивный характер в кузове SUV. Активная подвеска PASM, динамика на уровне 911 в городе.",
    features: F.premiumSuv,
  },
  {
    id: "range-rover-sport",
    name: "Range Rover Sport HSE",
    brand: "Land Rover",
    body: "suv",
    fuel: "diesel",
    transmission: "auto",
    price: 14800000,
    year: 2026,
    image: IMG.suv4,
    engine: "3.0 D300 MHEV",
    power: 300,
    acceleration: 6.6,
    topSpeed: 234,
    consumption: "8.1 л/100 км",
    description:
      "Британский премиум с настоящими внедорожными возможностями. Terrain Response 2, активные стабилизаторы, тихий салон.",
    features: F.premiumSuv,
  },
  {
    id: "lexus-lx",
    name: "LX 600",
    brand: "Lexus",
    body: "suv",
    fuel: "gasoline",
    transmission: "auto",
    price: 16500000,
    year: 2026,
    image: IMG.suv2,
    engine: "3.5 V6 Twin-Turbo",
    power: 415,
    acceleration: 6.9,
    topSpeed: 210,
    consumption: "11.2 л/100 км",
    description:
      "Японская роскошь с настоящей рамой и пневмоподвеской. Семиместный, тихий, не ломается.",
    features: F.premiumSuv,
  },

  // ===== Премиум-седаны =====
  {
    id: "bmw-5",
    name: "530i xDrive",
    brand: "BMW",
    body: "sedan",
    fuel: "gasoline",
    transmission: "auto",
    price: 7200000,
    year: 2026,
    image: IMG.sedan3,
    engine: "2.0 R4 TwinPower Turbo",
    power: 252,
    acceleration: 6.4,
    topSpeed: 250,
    consumption: "7.4 л/100 км",
    description:
      "Бизнес-седан с азартом BMW. iDrive 8.5, лазерные фары, отделка Sensatec по умолчанию.",
    features: F.premiumSedan,
  },
  {
    id: "mercedes-e",
    name: "E 300 4MATIC",
    brand: "Mercedes-Benz",
    body: "sedan",
    fuel: "gasoline",
    transmission: "auto",
    price: 8100000,
    year: 2026,
    image: IMG.sedan2,
    engine: "2.0 R4 EQ Boost",
    power: 258,
    acceleration: 6.2,
    topSpeed: 250,
    consumption: "7.5 л/100 км",
    description:
      "Эталон представительского седана. MBUX Superscreen, активные ассистенты, тишина в салоне.",
    features: F.premiumSedan,
  },
  {
    id: "audi-a6",
    name: "A6 55 TFSI quattro",
    brand: "Audi",
    body: "sedan",
    fuel: "gasoline",
    transmission: "auto",
    price: 7400000,
    year: 2026,
    image: IMG.sedan1,
    engine: "3.0 V6 TFSI",
    power: 340,
    acceleration: 5.1,
    topSpeed: 250,
    consumption: "8.1 л/100 км",
    description:
      "Технологичный бизнес-седан с продвинутой матричной оптикой и тремя экранами MMI touch response.",
    features: F.premiumSedan,
  },
  {
    id: "audi-a8",
    name: "A8 55 TFSI quattro",
    brand: "Audi",
    body: "sedan",
    fuel: "gasoline",
    transmission: "auto",
    price: 12800000,
    year: 2026,
    image: IMG.sedan2,
    engine: "3.0 V6 TFSI MHEV",
    power: 340,
    acceleration: 5.6,
    topSpeed: 250,
    consumption: "8.6 л/100 км",
    description:
      "Флагман Audi. Удлинённая колёсная база, активная подвеска предиктивного типа, массаж и климат для всех мест.",
    features: F.premiumSedan,
  },
  {
    id: "lexus-es",
    name: "ES 300h",
    brand: "Lexus",
    body: "sedan",
    fuel: "hybrid",
    transmission: "auto",
    price: 6200000,
    year: 2026,
    image: IMG.sedan1,
    engine: "2.5 R4 Hybrid",
    power: 218,
    acceleration: 8.1,
    topSpeed: 180,
    consumption: "4.9 л/100 км",
    description:
      "Гибридный седан премиум-класса. Минимальный расход, плавный ход и фирменная японская сборка Lexus.",
    features: F.premiumSedan,
  },
  {
    id: "genesis-g80",
    name: "G80 3.5T AWD",
    brand: "Genesis",
    body: "sedan",
    fuel: "gasoline",
    transmission: "auto",
    price: 6500000,
    year: 2026,
    image: IMG.sedan2,
    engine: "3.5 V6 Twin-Turbo",
    power: 380,
    acceleration: 5.1,
    topSpeed: 250,
    consumption: "10.4 л/100 км",
    description:
      "Корейская премиум-марка, бросившая вызов немецкой тройке. Тишина Lexus, ходовая BMW, цена дешевле обоих.",
    features: F.premiumSedan,
  },

  // ===== Среднеразмерные кроссоверы =====
  {
    id: "toyota-rav4",
    name: "RAV4 2.5 Hybrid",
    brand: "Toyota",
    body: "crossover",
    fuel: "hybrid",
    transmission: "auto",
    price: 4200000,
    year: 2026,
    image: IMG.suv3,
    engine: "2.5 R4 Hybrid",
    power: 222,
    acceleration: 8.4,
    topSpeed: 180,
    consumption: "5.0 л/100 км",
    description:
      "Бестселлер кроссоверов с гибридной установкой. Полный привод, низкий расход, проверенная электроника Toyota.",
    features: F.midCrossover,
  },
  {
    id: "mazda-cx-5",
    name: "CX-5 2.5 AWD",
    brand: "Mazda",
    body: "crossover",
    fuel: "gasoline",
    transmission: "auto",
    price: 3900000,
    year: 2026,
    image: IMG.suv2,
    engine: "2.5 R4 Skyactiv-G",
    power: 194,
    acceleration: 9.0,
    topSpeed: 204,
    consumption: "7.5 л/100 км",
    description:
      "Самый азартный в классе. Дизайн KODO, фирменное шасси Mazda, премиальный салон за разумные деньги.",
    features: F.midCrossover,
  },
  {
    id: "nissan-x-trail",
    name: "X-Trail 2.5 4WD",
    brand: "Nissan",
    body: "crossover",
    fuel: "gasoline",
    transmission: "auto",
    price: 3600000,
    year: 2026,
    image: IMG.suv1,
    engine: "2.5 R4",
    power: 184,
    acceleration: 10.5,
    topSpeed: 196,
    consumption: "7.8 л/100 км",
    description:
      "Семейный кроссовер с трёхрядной компоновкой и системой ProPILOT. Полный привод 4WD-i.",
    features: F.midCrossover,
  },
  {
    id: "honda-cr-v",
    name: "CR-V 1.5T AWD",
    brand: "Honda",
    body: "crossover",
    fuel: "gasoline",
    transmission: "auto",
    price: 4100000,
    year: 2026,
    image: IMG.suv2,
    engine: "1.5 R4 VTEC Turbo",
    power: 193,
    acceleration: 9.2,
    topSpeed: 200,
    consumption: "7.2 л/100 км",
    description:
      "Один из самых популярных кроссоверов в мире. Просторный салон, надёжный двигатель Honda, пакет Honda Sensing.",
    features: F.midCrossover,
  },
  {
    id: "subaru-forester",
    name: "Forester 2.5 Sport",
    brand: "Subaru",
    body: "crossover",
    fuel: "gasoline",
    transmission: "auto",
    price: 3800000,
    year: 2026,
    image: IMG.suv4,
    engine: "2.5 R4 Boxer",
    power: 184,
    acceleration: 9.5,
    topSpeed: 193,
    consumption: "7.9 л/100 км",
    description:
      "Симметричный полный привод и оппозитный двигатель Boxer. Любимец туристов и активных людей.",
    features: F.midCrossover,
  },
  {
    id: "kia-sportage",
    name: "Sportage 2.0 AWD",
    brand: "Kia",
    body: "crossover",
    fuel: "gasoline",
    transmission: "auto",
    price: 3200000,
    year: 2026,
    image: IMG.suv1,
    engine: "2.0 R4",
    power: 150,
    acceleration: 10.9,
    topSpeed: 195,
    consumption: "8.2 л/100 км",
    description:
      "Свежий дизайн с фирменными звёздами Tiger Eye. Просторный салон, изогнутый дисплей панели.",
    features: F.midCrossover,
  },
  {
    id: "hyundai-tucson",
    name: "Tucson 2.5 AWD",
    brand: "Hyundai",
    body: "crossover",
    fuel: "gasoline",
    transmission: "auto",
    price: 3100000,
    year: 2026,
    image: IMG.suv2,
    engine: "2.5 R4",
    power: 180,
    acceleration: 9.3,
    topSpeed: 201,
    consumption: "8.0 л/100 км",
    description:
      "Параметрический дизайн фар. Большой багажник, гарантия 5 лет, фирменное оборудование Hyundai SmartSense.",
    features: F.midCrossover,
  },
  {
    id: "skoda-karoq",
    name: "Karoq 1.4 TSI",
    brand: "Skoda",
    body: "crossover",
    fuel: "gasoline",
    transmission: "auto",
    price: 2900000,
    year: 2026,
    image: IMG.suv3,
    engine: "1.4 R4 TSI",
    power: 150,
    acceleration: 9.7,
    topSpeed: 198,
    consumption: "6.5 л/100 км",
    description:
      "Чешский кроссовер на платформе VW. Знаменитые Simply Clever-решения и щедрая базовая комплектация.",
    features: F.midCrossover,
  },

  // ===== Электромобили =====
  {
    id: "tesla-model-3",
    name: "Model 3 Long Range",
    brand: "Tesla",
    body: "sedan",
    fuel: "electric",
    transmission: "auto",
    price: 5900000,
    year: 2026,
    image: IMG.ev2,
    engine: "Два электромотора 366 кВт",
    power: 498,
    acceleration: 4.4,
    topSpeed: 233,
    consumption: "14.6 кВт·ч/100 км",
    description:
      "Самый продаваемый электроседан. Тихий, быстрый, программные обновления повышают функционал со временем.",
    features: F.ev(629, "до 80% за 25 мин"),
  },
  {
    id: "bmw-ix3",
    name: "iX3 M Sport",
    brand: "BMW",
    body: "crossover",
    fuel: "electric",
    transmission: "auto",
    price: 7200000,
    year: 2026,
    image: IMG.ev1,
    engine: "Электромотор 210 кВт",
    power: 286,
    acceleration: 6.8,
    topSpeed: 180,
    consumption: "18.5 кВт·ч/100 км",
    description:
      "Электрический X3 в премиум-исполнении. Те же ходовые качества, что и у бензинового, но без шума и заправок.",
    features: F.ev(461, "до 80% за 32 мин"),
  },
  {
    id: "audi-q4-etron",
    name: "Q4 50 e-tron quattro",
    brand: "Audi",
    body: "crossover",
    fuel: "electric",
    transmission: "auto",
    price: 6800000,
    year: 2026,
    image: IMG.ev2,
    engine: "Два электромотора 220 кВт",
    power: 299,
    acceleration: 6.2,
    topSpeed: 180,
    consumption: "17.4 кВт·ч/100 км",
    description:
      "Электрокроссовер с фирменным quattro. AR-проекция на лобовом стекле, премиальный салон Audi.",
    features: F.ev(488, "до 80% за 36 мин"),
  },
  {
    id: "volvo-ex30",
    name: "EX30 Twin Motor Performance",
    brand: "Volvo",
    body: "crossover",
    fuel: "electric",
    transmission: "auto",
    price: 4900000,
    year: 2026,
    image: IMG.ev1,
    engine: "Два электромотора 315 кВт",
    power: 428,
    acceleration: 3.6,
    topSpeed: 180,
    consumption: "16.8 кВт·ч/100 км",
    description:
      "Самый быстрый Volvo в истории. Компактный, минималистичный салон в скандинавском стиле, переработанные материалы.",
    features: F.ev(450, "до 80% за 28 мин"),
  },
  {
    id: "polestar-2",
    name: "Polestar 2 Long Range Dual Motor",
    brand: "Polestar",
    body: "sedan",
    fuel: "electric",
    transmission: "auto",
    price: 5400000,
    year: 2026,
    image: IMG.ev2,
    engine: "Два электромотора 310 кВт",
    power: 421,
    acceleration: 4.5,
    topSpeed: 205,
    consumption: "17.1 кВт·ч/100 км",
    description:
      "Электроседан от спортивного подразделения Volvo. Минималистичный скандинавский дизайн, Android Automotive на борту.",
    features: F.ev(591, "до 80% за 30 мин"),
  },

  // ===== Массовые седаны =====
  {
    id: "honda-accord",
    name: "Accord 2.0 Hybrid",
    brand: "Honda",
    body: "sedan",
    fuel: "hybrid",
    transmission: "auto",
    price: 4100000,
    year: 2026,
    image: IMG.sedan3,
    engine: "2.0 R4 e:HEV",
    power: 204,
    acceleration: 7.9,
    topSpeed: 200,
    consumption: "4.8 л/100 км",
    description:
      "Гибридный седан с просторным салоном и фирменной плавностью хода Honda. 10-летняя гарантия на батарею.",
    features: F.massSedan,
  },
  {
    id: "mazda-6",
    name: "Mazda6 2.5",
    brand: "Mazda",
    body: "sedan",
    fuel: "gasoline",
    transmission: "auto",
    price: 3700000,
    year: 2025,
    image: IMG.sedan1,
    engine: "2.5 R4 Skyactiv-G",
    power: 194,
    acceleration: 8.1,
    topSpeed: 220,
    consumption: "7.3 л/100 км",
    description:
      "Самый «европейский» японский седан. Острые рули, премиальный интерьер, лимитированная серия Carbon Edition.",
    features: F.massSedan,
  },
  {
    id: "skoda-octavia",
    name: "Octavia 1.4 TSI",
    brand: "Skoda",
    body: "sedan",
    fuel: "gasoline",
    transmission: "auto",
    price: 2800000,
    year: 2026,
    image: IMG.sedan2,
    engine: "1.4 R4 TSI",
    power: 150,
    acceleration: 8.5,
    topSpeed: 218,
    consumption: "6.4 л/100 км",
    description:
      "Лидер по соотношению «цена-качество-простор». Огромный багажник, Simply Clever-решения, экономичный TSI.",
    features: F.massSedan,
  },
  {
    id: "vw-passat",
    name: "Passat 2.0 TSI",
    brand: "Volkswagen",
    body: "sedan",
    fuel: "gasoline",
    transmission: "auto",
    price: 3400000,
    year: 2026,
    image: IMG.sedan1,
    engine: "2.0 R4 TSI",
    power: 220,
    acceleration: 7.2,
    topSpeed: 240,
    consumption: "7.1 л/100 км",
    description:
      "Бизнес-седан немецкого качества. Адаптивная подвеска DCC, цифровая панель Digital Cockpit Pro.",
    features: F.massSedan,
  },
  {
    id: "hyundai-sonata",
    name: "Sonata 2.5 Smartstream",
    brand: "Hyundai",
    body: "sedan",
    fuel: "gasoline",
    transmission: "auto",
    price: 3100000,
    year: 2026,
    image: IMG.sedan2,
    engine: "2.5 R4 GDI",
    power: 180,
    acceleration: 8.7,
    topSpeed: 210,
    consumption: "7.5 л/100 км",
    description:
      "Семейный седан с заметным дизайном. Дистанционная парковка, гарантия 5 лет, премиум-аудио Bose.",
    features: F.massSedan,
  },

  // ===== Китайские и бюджетные кроссоверы =====
  {
    id: "geely-coolray",
    name: "Coolray 1.5T Flagship",
    brand: "Geely",
    body: "crossover",
    fuel: "gasoline",
    transmission: "auto",
    price: 2300000,
    year: 2026,
    image: IMG.suv1,
    engine: "1.5 R3 Turbo",
    power: 150,
    acceleration: 7.9,
    topSpeed: 200,
    consumption: "7.4 л/100 км",
    description:
      "Самый продаваемый китайский кроссовер в РФ. Дизайн от Питера Хорбери (ex-Volvo), щедрая комплектация.",
    features: F.budgetCrossover,
  },
  {
    id: "geely-atlas",
    name: "Atlas Pro 2.0T 4WD",
    brand: "Geely",
    body: "crossover",
    fuel: "gasoline",
    transmission: "auto",
    price: 2800000,
    year: 2026,
    image: IMG.suv2,
    engine: "2.0 R4 Turbo",
    power: 218,
    acceleration: 8.4,
    topSpeed: 200,
    consumption: "8.6 л/100 км",
    description:
      "Семейный среднеразмерник с полным приводом и панорамной крышей. Хорошая «оснащёнка» уже в базе.",
    features: F.budgetCrossover,
  },
  {
    id: "chery-tiggo-7-pro",
    name: "Tiggo 7 Pro Max",
    brand: "Chery",
    body: "crossover",
    fuel: "gasoline",
    transmission: "auto",
    price: 2400000,
    year: 2026,
    image: IMG.suv3,
    engine: "1.6 R4 Turbo",
    power: 186,
    acceleration: 8.0,
    topSpeed: 195,
    consumption: "8.0 л/100 км",
    description:
      "Бестселлер Chery в России. Два экрана по 12.3 дюйма, премиальная отделка, гарантия 7 лет.",
    features: F.budgetCrossover,
  },
  {
    id: "chery-tiggo-8-pro",
    name: "Tiggo 8 Pro Max 4WD",
    brand: "Chery",
    body: "crossover",
    fuel: "gasoline",
    transmission: "auto",
    price: 2900000,
    year: 2026,
    image: IMG.suv1,
    engine: "2.0 R4 Turbo",
    power: 254,
    acceleration: 7.5,
    topSpeed: 200,
    consumption: "8.8 л/100 км",
    description:
      "Семиместный кроссовер для большой семьи. Активный полный привод, премиум-салон Nappa, аудио Sony.",
    features: F.budgetCrossover,
  },
  {
    id: "haval-jolion",
    name: "Jolion 1.5T",
    brand: "Haval",
    body: "crossover",
    fuel: "gasoline",
    transmission: "auto",
    price: 2100000,
    year: 2026,
    image: IMG.suv2,
    engine: "1.5 R4 Turbo",
    power: 150,
    acceleration: 11.3,
    topSpeed: 175,
    consumption: "7.9 л/100 км",
    description:
      "Стильный компакт от Great Wall. Большой 12.3\" экран, голосовое управление, экономичный турбомотор.",
    features: F.budgetCrossover,
  },
  {
    id: "haval-f7",
    name: "F7 2.0T 4WD",
    brand: "Haval",
    body: "crossover",
    fuel: "gasoline",
    transmission: "auto",
    price: 2600000,
    year: 2026,
    image: IMG.suv3,
    engine: "2.0 R4 Turbo",
    power: 190,
    acceleration: 9.4,
    topSpeed: 200,
    consumption: "8.5 л/100 км",
    description:
      "Среднеразмерник с настоящим полным приводом и фирменным TankTurn. Кожаный салон и панорамная крыша в базе.",
    features: F.budgetCrossover,
  },

  // ===== Хэтчбеки =====
  {
    id: "vw-golf",
    name: "Golf 1.5 eTSI",
    brand: "Volkswagen",
    body: "hatchback",
    fuel: "gasoline",
    transmission: "auto",
    price: 2700000,
    year: 2026,
    image: IMG.coupe2,
    engine: "1.5 R4 eTSI Mild Hybrid",
    power: 150,
    acceleration: 8.4,
    topSpeed: 224,
    consumption: "5.4 л/100 км",
    description:
      "Эталон C-сегмента с 1974 года. Лёгкий гибрид 48V, цифровая панель Digital Cockpit, IQ.LIGHT.",
    features: F.hatchback,
  },
  {
    id: "skoda-scala",
    name: "Scala 1.5 TSI",
    brand: "Skoda",
    body: "hatchback",
    fuel: "gasoline",
    transmission: "auto",
    price: 2200000,
    year: 2026,
    image: IMG.sedan1,
    engine: "1.5 R4 TSI",
    power: 150,
    acceleration: 8.2,
    topSpeed: 220,
    consumption: "5.7 л/100 км",
    description:
      "Чешский ответ Golf. Тот же мотор, цена ниже, багажник самый большой в классе.",
    features: F.hatchback,
  },
  {
    id: "kia-rio",
    name: "Rio X 1.6 AT",
    brand: "Kia",
    body: "hatchback",
    fuel: "gasoline",
    transmission: "auto",
    price: 1800000,
    year: 2025,
    image: IMG.sedan2,
    engine: "1.6 R4 Gamma",
    power: 123,
    acceleration: 11.3,
    topSpeed: 185,
    consumption: "7.6 л/100 км",
    description:
      "Городской хэтчбек с большим клиренсом. Apple CarPlay, гарантия 5 лет, низкая стоимость обслуживания.",
    features: F.hatchback,
  },
  {
    id: "hyundai-solaris",
    name: "Solaris 1.6 AT",
    brand: "Hyundai",
    body: "hatchback",
    fuel: "gasoline",
    transmission: "auto",
    price: 1700000,
    year: 2025,
    image: IMG.sedan1,
    engine: "1.6 R4 Gamma",
    power: 123,
    acceleration: 11.2,
    topSpeed: 190,
    consumption: "7.4 л/100 км",
    description:
      "Самая популярная иномарка в РФ за последние 10 лет. Просто, надёжно, дёшево в обслуживании.",
    features: F.hatchback,
  },

  // ===== Спорт и купе =====
  {
    id: "bmw-m4",
    name: "M4 Competition",
    brand: "BMW",
    body: "coupe",
    fuel: "gasoline",
    transmission: "auto",
    price: 12900000,
    year: 2026,
    image: IMG.coupe1,
    engine: "3.0 R6 M TwinPower Turbo",
    power: 530,
    acceleration: 3.5,
    topSpeed: 290,
    consumption: "10.2 л/100 км",
    description:
      "M-серия в чистом виде. Двойные ноздри Hofmeister-kink, ковшеобразные кресла M Carbon, активный дифференциал.",
    features: F.sportsCoupe,
  },
  {
    id: "mercedes-amg-gt",
    name: "AMG GT 63 4MATIC+",
    brand: "Mercedes-AMG",
    body: "coupe",
    fuel: "gasoline",
    transmission: "auto",
    price: 17800000,
    year: 2026,
    image: IMG.coupe2,
    engine: "4.0 V8 BiTurbo",
    power: 585,
    acceleration: 3.2,
    topSpeed: 315,
    consumption: "12.3 л/100 км",
    description:
      "Спортивный GT от AMG. Производится вручную в Аффальтербахе, идеальная развесовка благодаря трансмиссии в задней оси.",
    features: F.sportsCoupe,
  },
  {
    id: "audi-rs5",
    name: "RS5 Sportback",
    brand: "Audi",
    body: "coupe",
    fuel: "gasoline",
    transmission: "auto",
    price: 14500000,
    year: 2026,
    image: IMG.coupe3,
    engine: "2.9 V6 BiTurbo",
    power: 450,
    acceleration: 3.9,
    topSpeed: 280,
    consumption: "9.7 л/100 км",
    description:
      "Спортивный sportback с фирменным quattro. Динамика суперкара в кузове 5-дверки.",
    features: F.sportsCoupe,
  },

  // ===== Volvo (премиум-средний) =====
  {
    id: "volvo-xc60",
    name: "XC60 B5 AWD",
    brand: "Volvo",
    body: "crossover",
    fuel: "hybrid",
    transmission: "auto",
    price: 6800000,
    year: 2026,
    image: IMG.suv2,
    engine: "2.0 R4 Mild Hybrid",
    power: 250,
    acceleration: 6.9,
    topSpeed: 220,
    consumption: "7.2 л/100 км",
    description:
      "Скандинавский премиум. Сертифицированные ремни безопасности 6-го поколения, переработанные материалы салона.",
    features: F.premiumSuv,
  },
  {
    id: "volvo-xc90",
    name: "XC90 B6 AWD",
    brand: "Volvo",
    body: "suv",
    fuel: "hybrid",
    transmission: "auto",
    price: 9200000,
    year: 2026,
    image: IMG.suv3,
    engine: "2.0 R4 Mild Hybrid",
    power: 300,
    acceleration: 6.7,
    topSpeed: 220,
    consumption: "8.0 л/100 км",
    description:
      "Эталон семейной безопасности. Семиместный салон, аудио Bowers & Wilkins, фирменный молот Тора в фарах.",
    features: F.premiumSuv,
  },
];

export const ALL_BRANDS = Array.from(new Set(cars.map((c) => c.brand))).sort();
export const ALL_BODIES = Array.from(new Set(cars.map((c) => c.body)));
export const ALL_FUELS = Array.from(new Set(cars.map((c) => c.fuel)));

export const formatPrice = (price: number) =>
  new Intl.NumberFormat("ru-RU").format(price) + " ₽";

export const getCar = (id: string) => cars.find((c) => c.id === id);

export const getSimilarCars = (car: Car, limit = 3) =>
  cars.filter((c) => c.id !== car.id && c.body === car.body).slice(0, limit);
